Turkish Translat
Exodus-Privacy/exodus-android-app pull request #160
Opened 2022-04-24 16:49 UTC by metezd

2022-05-08 10:20 UTC, Jean-BaptisteC commented
Thanks for your work,
I wait 3.0 version (Kotlin Rewrite) to approve this pull request.

2022-07-12 20:27 UTC, Jean-BaptisteC commented
3.0 version is planned to september.
Can you update your commits with latest version of [strings.xml](https://github.com/Exodus-Privacy/exodus-android-app/blob/kotlinRewrite/app/src/main/res/values/strings.xml) ?

2022-07-16 13:22 UTC, Jean-BaptisteC requested changes
Thanks for translation.
Please check my comments.

2022-07-16 13:22 UTC, Jean-BaptisteC commented on app/src/main/res/values-tr/strings.xml
> +    <string name="app_title" translatable="false">εxodus</string>
Please remove there 8 strings with attributes translatable = false

2022-07-16 13:22 UTC, Jean-BaptisteC commented on app/src/main/res/values-tr/strings.xml
> +    <string name="srcCode_desc">Sorunları bildirin, yıldız verin, PR'lara katkıda bulunun veya kodu kontrol edin</string>
```suggestion
    <string name="srcCode_desc">Sorunları bildirin, yıldız verin, PR\'lara katkıda bulunun veya kodu kontrol edin</string>
```

2022-07-16 13:22 UTC, Jean-BaptisteC commented on app/src/main/res/values-tr/strings.xml
> +    <string name="warning_title">Exodus'un gerekli verileri iletmesine izin verilsin mi?</string>
```suggestion
    <string name="warning_title">Exodus\'un gerekli verileri iletmesine izin verilsin mi?</string>
```

2022-07-16 18:25 UTC, metezd commented
Updated all of them.

2022-08-28 18:33 UTC, Jean-BaptisteC approved these changes

2022-08-28 18:41 UTC, merged