Feat search through app lists
Exodus-Privacy/exodus-android-app pull request #215
Opened 2022-10-17 23:20 UTC by cchigo

add search functionality to search listed apps

2022-10-18 18:53 UTC, Jean-BaptisteC requested changes
Thanks for you work 🚀

Some changes:

2022-10-18 20:56 UTC, Jean-BaptisteC requested changes

2022-10-29 21:30 UTC, cchigo commented on app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt
>  import android.view.LayoutInflater
Hello, Please help explain the last line

2022-10-30 07:15 UTC, Jean-BaptisteC commented on app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt
>  import android.view.LayoutInflater
I have specify this line to explain that commentaries is about AppFragment.kt :)

2023-12-26 08:17 UTC, closed without merging