Issue 201
Exodus-Privacy/exodus-android-app pull request #263
Opened 2023-04-14 14:27 UTC by PatDyn

Should Solve Issue #201 

* We now do some minifying and resource shrinking while trying to keep a readable stack trace. 
    * this is done by a minimal proguard-rules.pro config
* Update okhttp3 dep to work with current R8 versions 
* Added a string.toLongOrZero() extension function to avoid type errors
* implement a signing config, that checks wether some env variables are set
    * thus deciding which origin to use for passwords
* Added a basic debug build type

Note:
No automated tests were implemented for this issue.

2023-04-16 08:10 UTC, Jean-BaptisteC requested changes
New management keystore failed when, i try to sync project on Android Studio and unable to build debug version because Android Studio didn't find keystore.properties file.

If you don't have a better solution, go back to older releaseConfig

2023-04-16 08:10 UTC, Jean-BaptisteC commented on app/src/main/res/values-fr/strings.xml
> +        <item quantity="many"><xliff:g id="percentage">%1$d</xliff:g>%% | <xliff:g id="apps">%2$d</xliff:g> apps</item>
```suggestion
        <item quantity="other"><xliff:g id="percentage">%1$d</xliff:g>%% | <xliff:g id="apps">%2$d</xliff:g> apps</item>
```
Crash with many on release version

2023-04-16 08:10 UTC, Jean-BaptisteC commented on app/src/main/res/values-fr/strings.xml
> +        <item quantity="many">Présent dans <xliff:g id="percentage">%1$d</xliff:g>%% (<xliff:g id="apps">%2$d</xliff:g> apps) de vos applications</item>
```suggestion
        <item quantity="other">Présent dans <xliff:g id="percentage">%1$d</xliff:g>%% (<xliff:g id="apps">%2$d</xliff:g> apps) de vos applications</item>
```

2023-04-18 07:23 UTC, PatDyn commented
> New management keystore failed when, i try to sync project on Android Studio and unable to build debug version because Android Studio didn't find keystore.properties file.
> 
> If you don't have a better solution, go back to older releaseConfig


Did you pull the latest changes? Because i refactored the releaseConfig {} so it does not look up the keystore.properties anymore. Also, can you please post logs of the error?

2023-04-19 16:12 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 13

2023-04-19 16:12 UTC, merged