Update X icons, strings and update icons
Exodus-Privacy/exodus-android-app pull request #325
Opened 2023-08-11 09:22 UTC by Jean-BaptisteC

- Fix #324
- Renamed somes icons
- Updated and optimized path
- Somes icons are now rounder
- Deleted unused icons

2023-08-11 11:37 UTC, codeurimpulsif requested changes

2023-08-11 11:37 UTC, codeurimpulsif commented on app/src/main/res/xml/about_preference.xml
>          android:key="twitter"
Don't you want to rename the `android:key` too?

2023-08-11 11:39 UTC, codeurimpulsif commented
Also, do you think it's a good idea to change this now? Everyone seem to still refer to this social network as "Twitter"

2023-08-11 11:55 UTC, Jean-BaptisteC commented
Next version is not planned for now (September or October, maybe).
I think a most of users know new name of Twitter, if you want, i keep new icon with older name ?

2023-08-11 11:57 UTC, codeurimpulsif commented
I don't know, maybe we can speak about this at the next meeting?

2023-08-13 08:12 UTC, Jean-BaptisteC commented
I have found a better way, I suggest for Twitter string `X (Twitter)`

2023-09-11 18:49 UTC, xakan approved these changes

2023-09-14 21:59 UTC, codeurimpulsif approved these changes

2023-09-15 04:59 UTC, merged