Update and improve readme
Exodus-Privacy/exodus-android-app pull request #388
Opened 2024-01-28 16:31 UTC by Jean-BaptisteC

2024-01-28 22:13 UTC, codeurimpulsif requested changes

2024-01-28 22:13 UTC, codeurimpulsif commented on README.md
> -- Join us on our [IRC channel #exodus-android-app on Libera.chat](https://web.libera.chat/?nick=webguest?#exodus-android-app) (also bridged on [Matrix channel #exodus-android-app:matrix.org](https://
Why removing the IRC link? It's working, only Matrix is unavailable now.

2024-01-29 08:07 UTC, Jean-BaptisteC commented on README.md
> -
Because we don't have unit tests, only instrumented tests.

2024-01-30 09:48 UTC, pnu-s approved these changes

2024-01-30 13:53 UTC, codeurimpulsif approved these changes

2024-01-30 14:18 UTC, merged