Improve transitions & add animation to hide bottom bar
Exodus-Privacy/exodus-android-app pull request #439
Opened 2024-04-26 10:01 UTC by starry-shivam

Before

https://github.com/Exodus-Privacy/exodus-android-app/assets/58552395/aac2ced7-aaf7-4088-8692-0c4587b1cb37

After

https://github.com/Exodus-Privacy/exodus-android-app/assets/58552395/98fd53f0-3faf-4a7e-9e0e-075727de65ba

Closes #346

2024-04-26 10:41 UTC, starry-shivam commented
I noticed that @rohit9625 had already requested work on this, but it seems that three months have passed without any activity. Therefore, I decided to create a PR.

2024-04-26 18:01 UTC, Jean-BaptisteC requested changes
Wow animations are beautiful 🤩

Please fix linter

2024-04-26 18:06 UTC, starry-shivam commented
> Wow animations are beautiful 🤩
> 
> Please fix linter

Thanks! I'll fix linter errors tomorrow.

2024-04-27 05:24 UTC, Jean-BaptisteC approved these changes

2024-04-27 05:24 UTC, merged